name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: sudo make install-prerequisites

      - name: Generate
        run: make gen

      - name: Build
        run: make build

      - name: Test
        run: make test
